### ISSUE TITLE
Leaflet.Hash disables mouse zooming

### ISSUE THREAD

**Issue by almereyda** [tangrams/generic-demo#1]
As long as Leaflet.Hash is loaded, mouse scrolling will yield:

```
mapzen.com/tangram/tangram.min.js:10 Uncaught TypeError: e._move is not a function
```

How to proceed from here?
- Does Tangram need an update to be compatible with https://github.com/mlevans/leaflet-hash
- or do we need to send a PR to https://github.com/mlevans/leaflet-hash to make it work properly again?

It seems someone is stealing events here.

**Comment by meetar** [comment]
Thanks for the issue – I'm seeing this error whether leaflet.hash is loaded or not. Tangram was just upgraded to use the new Leaflet v 1.0 beta, and we've been making modifications to the library to accommodate. This will be addressed in the next Tangram release, so I'll move this issue there and rename it.

**Comment by meetar** [comment]
This issue was moved to tangrams/tangram#199
